services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    env_file:
      - .env
    environment:
      - PGPORT=5432

  backend:
    image: "fastapi-template:latest"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PORT=8000
      - POSTGRES_SERVER=db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"