"""Initial Migration

Revision ID: 17315875f468
Revises: 
Create Date: 2024-10-28 12:13:09.891633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = '17315875f468'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', app.sqltypes.EncryptedText(), nullable=False),
        sa.Column('password', sa.Text(), nullable=False),
        sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHERS', name='gender_enum'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column(
            'date_joined',
            sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False
        ),
        sa.Column(
            'last_login',
            sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False
        ),
        sa.Column(
            'last_active',
            sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False
        ),
        sa.Column('key_version', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='public')
    sa.Enum(name='gender_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
